src/pitchit/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from .views import IndexView, ConfirmView, formulieren

app_name = 'pitchit'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^confirm/(?P<uuid>\w+)/', ConfirmView.as_view(),
        name='survey-confirmation'),
    url(r'^formulieren/$', formulieren, name='formulieren'),
]

src/survey/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from .views import SurveyDetail, SurveyCompleted, ConfirmView, SurveyResultData

app_name = 'survey'
urlpatterns = [
    url(r'^(?P<id>\d+)/', SurveyDetail.as_view(), name='survey-detail'),
    url(r'^(?P<id>\d+)-(?P<step>\d+)/', SurveyDetail.as_view(),
        name='survey-detail-step'),
    url(r'^(?P<id>\d+)/completed/', SurveyCompleted.as_view(),
        name='survey-completed'),
    url(r'^confirm/(?P<uuid>\w+)/', ConfirmView.as_view(),
        name='survey-confirmation'),
    url(r'^resultdata/(?P<id>\d+)/', SurveyResultData.as_view(), name='survey-result-data'),
]

src/tools/urls.py
from __future__ import unicode_literals
from django.conf.urls import url

from .views import (
    index,
)

urlpatterns = [
    url(r'^$', index, name='index'),
]

src/pitchit/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from survey.models import Survey

# Create your models here.


class PageContent(models.Model):
    naam = models.SlugField(unique=True,
                            help_text=('Voor de hoofdpagina moet dit "index" zijn'),)
    published = models.BooleanField(default=True,
                                    verbose_name=_("Published"),
                                    help_text=('Aanvinken als pagina getoond moet worden'),)
    titel = models.CharField(max_length=64)
    intro = models.CharField(max_length=2000,
                             blank=True,
                             help_text=('Maximaal 2000 characters'),)
    content = models.TextField(verbose_name=_("Content"),
                               help_text=('De pagina inhoud'),)
    formulier = models.ForeignKey(Survey, blank=True, null=True,
                                  related_name="pitchit_formulier")

    def __str__(self):
        return self.titel

src/pitchit/views.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.contrib.auth.decorators import permission_required
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import TemplateView, View

from survey.forms import ResponseForm
from survey.models import Answer, Category, Survey

from .models import PageContent

# Create your views here.


class IndexView(View):

    def get(self, request, *args, **kwargs):
        page = get_object_or_404(PageContent, naam='index')
        if not page.published:
            raise Http404()
        survey = page.formulier
        categories = form = None
        if survey:
            if survey.need_logged_user and not request.user.is_authenticated():
                return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
            categories = Category.objects.filter(
                survey=survey).order_by('order')
            form = ResponseForm(survey=survey, user=None,
                                step=kwargs.get('step', 0))
        template_name = "pitchit/index.html"
        context = {
            'page': page,
            'response_form': form,
            'survey': survey,
            'categories': categories,
        }
        return render(request, template_name, context)

    def post(self, request, *args, **kwargs):
        page = get_object_or_404(PageContent, naam='index')
        if not page.published:
            raise Http404()
        survey = page.formulier
        categories = form = None
        if survey:
            if survey.need_logged_user and not request.user.is_authenticated():
                return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
            categories = Category.objects.filter(
                survey=survey).order_by('order')
            form = ResponseForm(request.POST, survey=survey, user=None,
                                step=kwargs.get('step', 0))
            if form.is_valid():
                response = form.save()
                return redirect('pitchit:survey-confirmation', uuid=response.interview_uuid)
        template_name = "pitchit/index.html"
        context = {
            'page': page,
            'response_form': form,
            'survey': survey,
            'categories': categories,
        }
        return render(request, template_name, context)


class ConfirmView(TemplateView):

    template_name = 'pitchit/confirm.html'

    def get_context_data(self, **kwargs):
        context = super(ConfirmView, self).get_context_data(**kwargs)
        page = get_object_or_404(PageContent, naam='index')
        if not page.published:
            raise Http404()
        context['uuid'] = kwargs['uuid']
        context['page'] = page
        return context


@permission_required('pitchit.change_pagecontent')
def formulieren(request):
    page = get_object_or_404(PageContent, naam='index')
    survey = page.formulier
    if not survey:
        raise Http404()
    template_name = 'pitchit/formulieren.html'
    context = {
        'page': page,
        'survey': survey,
    }
    return render(request, template_name, context)

src/pitchit/templates/pitchit/confirm.html
{% extends "mainscreen/base.html" %}
{% load static %}
{% load i18n %}
{% block title %}{{ page.titel }} | UBR|V-Lab{% endblock %}

{% block navbar %}
<nav class="breadCrumbNav">
    <span class="assistive">U bevindt zich hier:</span>
    <a href="https://www.ubrijk.nl/organisatie/ubr/ubr-v-lab">UBR|V-Lab</a>
    <a href="{% url 'pitchit:index' %}">{{ page.titel }}</a>
    <span>Bevestiging</span>
</nav>
{% endblock %}

{% block content %}
<div id="content" class="article">
    <h1>{% trans "Formulier verzonden"%}</h1>
    <p>
        <div class="alert alert-success">
            {% trans "Bedankt voor uw reactie!" %}
        </div>
    </p>
</div>
{% endblock %}

src/pitchit/templates/pitchit/formulieren.html
{% extends "mainscreen/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{{ page.titel }} | UBR|V-Lab{% endblock %}

{% block navbar %}
<nav class="breadCrumbNav">
  <span class="assistive">U bevindt zich hier:</span>
  <a href="https://www.ubrijk.nl/organisatie/ubr/ubr-v-lab">UBR|V-Lab</a>
  <a href="{% url 'pitchit:index' %}">{{ page.titel }}</a>
  <span>Formulieren</span>
</nav>
{% endblock %}

{% block content %}
<div id="content" class="article">
  <style>
    .intrinsic-container {
      position: relative;
      height: 0;
      overflow: hidden;
      margin-bottom: 1.5rem;
    }

    .intrinsic-container-16x9 {
      padding-bottom: 56.25%
    }

    .intrinsic-container-4x3 {
      padding-bottom: 75%
    }

    .intrinsic-container-1x2 {
      padding-bottom: 200%
    }

    .intrinsic-container iframe {
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      margin: 0!important;
      border: 2px solid #ccc;
    }
  </style>
  <div class="intrinsic-container intrinsic-container-1x2">
    <iframe src="{% url 'survey:survey-result-data' id=survey.pk %}" frameborder="0"></iframe>
  </div>
</div>
{% endblock %}

src/pitchit/templates/pitchit/index.html
{% extends "mainscreen/base.html" %}
{% load static %}
{% load i18n %}
{% load survey_extras %}

{% block title %}{{ page.titel }} | UBR|V-Lab{% endblock %}

{% block navbar %}
<nav class="breadCrumbNav">
  <span class="assistive">U bevindt zich hier:</span>
  <a href="https://www.ubrijk.nl/organisatie/ubr/ubr-v-lab">UBR|V-Lab</a>
  <span>{{ page.titel }}</span>
</nav>
{% endblock %}

{% block subnavigation %}
{% if survey and perms.pitchit.change_pagecontent %}
<div class="subNavigation">
  <div class="wrapper">
    <ul>
      <li><a href="{% url 'pitchit:formulieren' %}">Toon ingevulde formulieren</a></li>
    </ul>
	</div>
</div>
{% endif %}
{% endblock %}

{% block content %}
<div id="content" class="article">
  {% if page.intro %}
  <div class="intro">
    <p>{{ page.intro|safe }}</p>
  </div>
  {% endif %}
  {{ page.content|safe }}
  {% if survey %}
  <div class="container" id="wrap">
    <div class="well" id="container-main">
      <div class="form fancy">
        <div id="usage_simple" style="position:relative;">
          <form action="{% url 'pitchit:index' %}" method="post" id="survey_form" autocomplete="off">
            {% if response_form.non_field_errors %}
            <div class="message error">
              <p>Er zijn één of meerdere velden niet of niet juist ingevuld. Controleer uw gegevens en verstuur het formulier
                opnieuw.</p>{{ response_form.non_field_errors }}</div>
            {% endif %} {% csrf_token %}
            <div class="formWrapper eform">
              <div id="page0" class="eforms-page conditionally-visible">
                <div class="eformText">
                  <h2 class="req">{{survey.soort}}</h2>
                  <p class="meta req">* verplichte velden</p>
                </div>
                {% for category in categories %}
                <h3>{{category}}</h3>
                {% if category.description %}
                <p>{{category.description}}</p>
                {% endif %}
                {% include "survey/question.html" %}
                {% empty %}
                <h3> {% trans "Vul onderstaande gegevens in" %} </h3>
                {% include "survey/question.html" %}
                {% endfor %}
                {% include "survey/akkoordverklaring.html" %}
              </div>
              <div class="eforms-buttons">
                <input type="submit" id="confirm-button" name="confirm" class="" value="Ga verder" />
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  {% endif %}
</div>
{% if perms.pitchit.change_pagecontent %}
<div id="aside">
  <div class="brick linkBlock">
    <h2>Beheer</h2>
    <ul class="common">
      <li>
        <a href="{% url 'admin:pitchit_pagecontent_change' page.pk %}" class="common">Wijzigen pagina inhoud</a>
      </li>
    </ul>
  </div>
</div>
{% endif %}
{% endblock %}