src/conference/urls.py
from django.conf.urls import url

from .views import section_list

urlpatterns = [
    url(r'^(?P<slug>[-\w\d\_]+)/$', section_list, name="section_list"),
]

src/evenementen/urls.py
from django.conf.urls import url

from . import views

app_name = 'evenementen'
urlpatterns = [
    url(r'^evenementen/$', views.evenementen, name='evenementen'),
    url(r'^historie/$', views.historie, name='historie'),
    url(r'^evenement-aanmeldingen/(?P<slug>[-\w\d\_]+)/$',
        views.evenement_aanmeldingen, name='evenement_aanmeldingen'),
    url(r'^evenement-evaluaties/(?P<slug>[-\w\d\_]+)/$',
        views.evenement_evaluaties, name='evenement_evaluaties'),
    url(r'^evenement/voegtoe/$', views.evenement_voegtoe, name='evenement_voegtoe'),
    url(r'^evenement/(?P<slug>[-\w\d\_]+)/wijzig/$',
        views.evenement_wijzig, name='evenement_wijzig'),
    url(r'^evenementen/(?P<slug>[-\w\d\_]+)/$',
        views.evenement_overzicht, name='evenement_overzicht'),
]

src/schedule/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from .views import (promote, schedule_conference, schedule_edit,
                    schedule_presentation_detail, schedule_slot_edit)

app_name = 'schedule'
urlpatterns = [
    url(r'^(?P<slug>[-\w\d\_]+)/$', schedule_conference,
        name="schedule_conference"),
    url(r"^(?P<slug>[-\w\d\_]+)/presentatie/(?P<pk>[0-9]+)/$",
        schedule_presentation_detail, name="schedule_presentation_detail"),
    url(r"^([\w\-]+)/edit/$", schedule_edit, name="schedule_edit"),
    url(r"^([\w\-]+)/edit/slot/(\d+)/",
        schedule_slot_edit, name="schedule_slot_edit"),
    url(r"^([\w\-]+)/promote/$", promote, name="promote"),
]

src/tools/urls.py
from __future__ import unicode_literals
from django.conf.urls import url

from .views import (
    index,
)

urlpatterns = [
    url(r'^$', index, name='index'),
]

src/conference/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible

from timezone_field import TimeZoneField


CONFERENCE_CACHE = {}


@python_2_unicode_compatible
class Conference(models.Model):
    """
    the full conference for a specific year, e.g. US PyCon 2012.
    """

    title = models.CharField(_("Title"), max_length=100)

    # when the conference runs
    start_date = models.DateField(_("Start date"), null=True, blank=True)
    end_date = models.DateField(_("End date"), null=True, blank=True)

    # timezone the conference is in
    timezone = TimeZoneField(blank=True, verbose_name=_("timezone"))

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super(Conference, self).save(*args, **kwargs)
        if self.id in CONFERENCE_CACHE:
            del CONFERENCE_CACHE[self.id]

    def delete(self):
        pk = self.pk
        super(Conference, self).delete()
        try:
            del CONFERENCE_CACHE[pk]
        except KeyError:
            pass

    class Meta(object):
        verbose_name = _("conference")
        verbose_name_plural = _("conferences")


@python_2_unicode_compatible
class Section(models.Model):
    """
    a section of the conference such as "Tutorials", "Workshops",
    "Talks", "Expo", "Sprints", that may have its own review and
    scheduling process.
    """

    conference = models.ForeignKey(Conference, verbose_name=_("Conference"))

    name = models.CharField(_("Name"), max_length=100)
    slug = models.SlugField(verbose_name=_("Slug"))

    # when the section runs
    start_date = models.DateTimeField(_("Start date"), null=True, blank=True)
    end_date = models.DateTimeField(_("End date"), null=True, blank=True)

    def __str__(self):
        return "%s %s" % (self.conference, self.name)

    class Meta(object):
        verbose_name = _("section")
        verbose_name_plural = _("sections")
        ordering = ["start_date"]


def current_conference():
    from django.conf import settings
    try:
        conf_id = settings.CONFERENCE_ID
    except AttributeError:
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured("You must set the CONFERENCE_ID setting.")
    try:
        current_conf = CONFERENCE_CACHE[conf_id]
    except KeyError:
        current_conf = Conference.objects.get(pk=conf_id)
        CONFERENCE_CACHE[conf_id] = current_conf
    return current_conf

src/conference/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render

from evenementen.models import Evenement

from .models import Section

# Create your views here.


@login_required
def section_list(request, slug):

    evenement = get_object_or_404(Evenement, slug=slug)

    if request.user.is_staff:
        sections = Section.objects.filter(
            conference__programma_evenement=evenement)
    else:
        sections = Section.objects.filter(
            conference__programma_evenement=evenement)
    ctx = {
        'evenement': evenement,
        "sections": sections,
    }
    return render(request, "conference/section_list.html", ctx)

src/conference/templates/conference/section_list.html
{% extends "mainscreen/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{{ evenement.naam }} | Programma | UBR|V-Lab{% endblock %}

{% block navbar %}
<nav class="breadCrumbNav">
  <span class="assistive">U bevindt zich hier:</span>
  <a href="https://www.ubrijk.nl/organisatie/ubr/ubr-v-lab">UBR|V-Lab</a>
  <a href="{% url 'evenementen:evenementen' %}">Evenementen</a>
  <a href="{{ evenement.get_absolute_url }}">{{ evenement.naam }}</a>
  <span>Aanpassen programma</span>
</nav>
{% endblock %}

{% block content %}
<div id="content" class="article">
  <h1 class="news">{{ evenement.naam }}</h1>
  <p class="article-meta">Programma</p>
  <dl>
    <dt>Datum:</dt>
    <dd>
      <time itemprop="startDate">{{ evenement.start_datum|date:"d F Y" }}</time>
      {% if evenement.einde_datum %} - <time itemprop="endDate">{{ evenement.einde_datum|date:"d F Y" }}</time>{% endif %}
    </dd>
	{% if evenement.locatie %}
    <dt>Locatie:</dt>
    <dd itemprop="location">{{ evenement.locatie }}</dd>
	{% endif %}
  </dl>
  <div class="common results">
    {% for section in sections %}
    <a href="{% url 'schedule:schedule_edit' section.slug %}" class="activity">
			<h3>{{ section.name }}</h3>
			{% if section.schedule %}
			<p class="meta">
				{{ section.schedule.published }}
				{% if evenement.einde_datum %} - {{ evenement.einde_datum|date:"d F Y" }}{% endif %}
				{% if evenement.locatie %} | {{ evenement.locatie }}{% endif %}
				<br>Programma
            </p>
            {% endif %}
		</a>
    {% endfor %}
</div>
</div>
{% endblock %}

src/conference/templates/conference/user_list.html
{% extends "site_base.html" %}

{% load i18n %}
{% load sitetree %}

{% block head_title %}User List{% endblock %}

{% block extra_style %}
    <style type="text/css">
        div.dataTables_length label {
            float: left;
            text-align: left;
        }

        div.dataTables_length select {
            width: 75px;
        }

        div.dataTables_filter label {
            float: right;
        }

        div.dataTables_info {
            padding-top: 8px;
        }

        div.dataTables_paginate {
            float: right;
            margin: 0;
        }

        table.table {
            clear: both;
            margin-bottom: 6px !important;
            background-color: white;
        }

        table.table thead .sorting,
        table.table thead .sorting_asc,
        table.table thead .sorting_desc,
        table.table thead .sorting_asc_disabled,
        table.table thead .sorting_desc_disabled {
            cursor: pointer;
            *cursor: hand;
        }

        table.dataTable th:active {
            outline: none;
        }
    </style>
{% endblock %}

{% block body_outer %}
    <h1>User List</h1>
    <table class="table table-striped table-bordered table-reviews">
        <thead>
            <th>{% trans "Email" %}</th>
            <th>{% trans "Name" %}</th>
            <th>{% trans "Speaker Profile?" %}</th>
        </thead>

        <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.email }}</td>
                    <td>{{ user.get_full_name }}</td>
                    <td>
                        {% if user.speaker_profile %}
                            <a href="{% url "speaker_profile" user.speaker_profile.pk %}">{{ user.speaker_profile }}</a>
                        {% else %}
                            <a href="{% url "speaker_create_staff" user.pk %}" class="btn btn-xs">create</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block extra_script %}
    <script src="{{ STATIC_URL }}datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}tabletools/js/TableTools.min.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}datatables/js/dataTables.bootstrap.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(function() {
            $(".tip").tooltip();
            $("table.table-reviews").dataTable({
                "sDom": "<'row'<'col-md-3'l><'col-md-3'T><'col-md-4'f>r>t<'row'<'col-md-3'i><'col-md-5'p>>",
                "sPaginationType": "bootstrap",
                "bStateSave": true,
                "oTableTools": {
                    "aButtons": [
                        "copy",
                        "csv",
                        "print"
                    ],
                    "sSwfPath": "{{ STATIC_URL }}tabletools/swf/copy_csv_xls.swf"
                }
            });
        });
    </script>
{% endblock %}