src/evenementen/urls.py
from django.conf.urls import url

from . import views

app_name = 'evenementen'
urlpatterns = [
    url(r'^evenementen/$', views.evenementen, name='evenementen'),
    url(r'^historie/$', views.historie, name='historie'),
    url(r'^evenement-aanmeldingen/(?P<slug>[-\w\d\_]+)/$',
        views.evenement_aanmeldingen, name='evenement_aanmeldingen'),
    url(r'^evenement-evaluaties/(?P<slug>[-\w\d\_]+)/$',
        views.evenement_evaluaties, name='evenement_evaluaties'),
    url(r'^evenement/voegtoe/$', views.evenement_voegtoe, name='evenement_voegtoe'),
    url(r'^evenement/(?P<slug>[-\w\d\_]+)/wijzig/$',
        views.evenement_wijzig, name='evenement_wijzig'),
    url(r'^evenementen/(?P<slug>[-\w\d\_]+)/$',
        views.evenement_overzicht, name='evenement_overzicht'),
]

src/schedule/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from .views import (promote, schedule_conference, schedule_edit,
                    schedule_presentation_detail, schedule_slot_edit)

app_name = 'schedule'
urlpatterns = [
    url(r'^(?P<slug>[-\w\d\_]+)/$', schedule_conference,
        name="schedule_conference"),
    url(r"^(?P<slug>[-\w\d\_]+)/presentatie/(?P<pk>[0-9]+)/$",
        schedule_presentation_detail, name="schedule_presentation_detail"),
    url(r"^([\w\-]+)/edit/$", schedule_edit, name="schedule_edit"),
    url(r"^([\w\-]+)/edit/slot/(\d+)/",
        schedule_slot_edit, name="schedule_slot_edit"),
    url(r"^([\w\-]+)/promote/$", promote, name="promote"),
]

src/survey/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from .views import SurveyDetail, SurveyCompleted, ConfirmView, SurveyResultData

app_name = 'survey'
urlpatterns = [
    url(r'^(?P<id>\d+)/', SurveyDetail.as_view(), name='survey-detail'),
    url(r'^(?P<id>\d+)-(?P<step>\d+)/', SurveyDetail.as_view(),
        name='survey-detail-step'),
    url(r'^(?P<id>\d+)/completed/', SurveyCompleted.as_view(),
        name='survey-completed'),
    url(r'^confirm/(?P<uuid>\w+)/', ConfirmView.as_view(),
        name='survey-confirmation'),
    url(r'^resultdata/(?P<id>\d+)/', SurveyResultData.as_view(), name='survey-result-data'),
]

src/tools/urls.py
from __future__ import unicode_literals
from django.conf.urls import url

from .views import (
    index,
)

urlpatterns = [
    url(r'^$', index, name='index'),
]

src/evenementen/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _
import itertools

# Create your models here.

from survey.models import Survey
from conference.models import Conference


class PageContent(models.Model):
    naam = models.SlugField(unique=True,
                            help_text=('Voor de hoofdpagina moet dit "index" zijn'),)
    published = models.BooleanField(default=True,
                                    verbose_name=_("Published"),
                                    help_text=('Aanvinken als pagina getoond moet worden'),)
    titel = models.CharField(max_length=64)
    intro = models.CharField(max_length=2000,
                             blank=True,
                             help_text=('Maximaal 2000 characters'),)
    content = models.TextField(verbose_name=_("Content"),
                               help_text=('De pagina inhoud'),)

    def __str__(self):
        return self.titel


class Evenement(models.Model):
    naam = models.CharField(max_length=200)
    intro = models.CharField(max_length=2000, blank=True)
    omschrijving = models.TextField()
    locatie = models.CharField(max_length=160, blank=True)
    start_datum = models.DateField()
    einde_datum = models.DateField(blank=True, null=True)
    aanmelding_formulier = models.ForeignKey(Survey, blank=True, null=True,
                                             related_name="aanmelding_evenement")
    evaluatie_formulier = models.ForeignKey(Survey, blank=True, null=True,
                                            related_name="evaluatie_evenement")
    programma = models.ForeignKey(Conference, blank=True, null=True,
                                  related_name="programma_evenement")
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.naam

    def get_absolute_url(self):
        return reverse('evenementen:evenement_overzicht', args=(self.slug,))

    def save(self, *args, **kwargs):
        if not self.pk:
            max_length = Evenement._meta.get_field('slug').max_length
            self.slug = orig = slugify(self.naam)[:max_length]
            for x in itertools.count(1):
                if not Evenement.objects.filter(slug=self.slug).exists():
                    break
                self.slug = "%s-%d" % (orig[:max_length - len(str(x)) - 1], x)
        # Call the "real" save() method.
        super(Evenement, self).save(*args, **kwargs)

src/evenementen/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget

from .models import Evenement

class EvenementForm(forms.ModelForm):
    def __init__(self, evenement_id=None, *args, **kwargs):
        super(EvenementForm, self).__init__(*args, **kwargs)
            
    class Meta:
        model = Evenement
        fields = '__all__'
        widgets = {
            # https://github.com/summernote/django-summernote
            'intro': SummernoteWidget(attrs={'width': '100%', 'height': '300px'}),
            'omschrijving': SummernoteWidget(attrs={'width': '100%', 'height': '300px'}),
            'start_datum': forms.DateInput(attrs={'class': 'date',
                                                  'size': 20,
                                                  'placeholder': 'DD-MM-JJJJ',
                                                  'data-format': 'DD-MM-JJJJ',
                                                  'data-nextmonth': 'Maand later',
                                                  'data-nextyear': 'Jaar later',
                                                  'data-prevmonth': 'Maand eerder',
                                                  'data-prevyear': 'Jaar eerder',
                                                  'data-close': 'Sluiten',
                                                  'data-button': 'Datum kiezen',
                                                  'data-tablecaption': 'Kies uit kalender',
                                                  'data-months': 'Januari, Februari, Maart, April, Mei, Juni, Juli, Augustus, September, Oktober, November, December',
                                                  'data-monthsshort': 'Jan, Feb, Maa, Apr, Mei, Jun, Jul, Aug, Sep, Okt, Nov, Dec',
                                                  'data-days': 'Zondag, Maandag, Dinsdag, Woensdag, Donderdag, Vrijdag, Zaterdag',
                                                  'data-daysshort': 'Zon, Maa, Din, Woe, Don, Vrij, Zat',
                                                  'data-daysmin': 'ZO, MA, DI, WO, DO, VR, ZA',
                                                  }
                                           ),
            'einde_datum': forms.DateInput(attrs={'class': 'date',
                                                  'size': 20,
                                                  'placeholder': 'DD-MM-JJJJ',
                                                  'data-format': 'DD-MM-JJJJ',
                                                  'data-nextmonth': 'Maand later',
                                                  'data-nextyear': 'Jaar later',
                                                  'data-prevmonth': 'Maand eerder',
                                                  'data-prevyear': 'Jaar eerder',
                                                  'data-close': 'Sluiten',
                                                  'data-button': 'Datum kiezen',
                                                  'data-tablecaption': 'Kies uit kalender',
                                                  'data-months': 'Januari, Februari, Maart, April, Mei, Juni, Juli, Augustus, September, Oktober, November, December',
                                                  'data-monthsshort': 'Jan, Feb, Maa, Apr, Mei, Jun, Jul, Aug, Sep, Okt, Nov, Dec',
                                                  'data-days': 'Zondag, Maandag, Dinsdag, Woensdag, Donderdag, Vrijdag, Zaterdag',
                                                  'data-daysshort': 'Zon, Maa, Din, Woe, Don, Vrij, Zat',
                                                  'data-daysmin': 'ZO, MA, DI, WO, DO, VR, ZA',
                                                  }
                                           ),
            }
    error_css_class = 'error'
    required_css_class = 'required'

src/evenementen/views.py
import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.core.urlresolvers import reverse
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render

from .forms import EvenementForm
from .models import Evenement, PageContent

# Create your views here.


def evenementen(request):
    page = get_object_or_404(PageContent, naam='index')
    if not page.published:
        raise Http404()
    template_name = 'evenementen/evenementen.html'
    evenement_list = Evenement.objects.filter(
        start_datum__gte=datetime.date.today())
    context = {
        'page': page,
        'evenement_list': evenement_list
    }
    return render(request, template_name, context)


def historie(request):
    page = get_object_or_404(PageContent, naam='index')
    if not page.published:
        raise Http404()
    template_name = 'evenementen/historie.html'
    evenement_list = Evenement.objects.filter(
        start_datum__lt=datetime.date.today())
    context = {
        'page': page,
        'evenement_list': evenement_list
    }
    return render(request, template_name, context)


def evenement_overzicht(request, slug):
    template_name = 'evenementen/evenement_overzicht.html'
    evenement = get_object_or_404(Evenement, slug=slug)
    context = {'evenement': evenement}
    return render(request, template_name, context)


@permission_required('evenementen.change_evenement')
def evenement_aanmeldingen(request, slug):
    template_name = 'evenementen/evenement_aanmeldingen.html'
    evenement = get_object_or_404(Evenement, slug=slug)
    context = {'evenement': evenement}
    return render(request, template_name, context)


@permission_required('evenementen.change_evenement')
def evenement_evaluaties(request, slug):
    template_name = 'evenementen/evenement_evaluaties.html'
    evenement = get_object_or_404(Evenement, slug=slug)
    context = {'evenement': evenement}
    return render(request, template_name, context)


@permission_required('evenementen.add_evenement')
def evenement_voegtoe(request):
    template_name = 'evenementen/evenement_voegtoe.html'
    if request.method == 'POST':
        form = EvenementForm(request.POST)
        if form.is_valid():
            evenement = form.save()
            messages.success(request, "Evenement toegevoegd.")
            return redirect(evenement.get_absolute_url())
    else:
        form = EvenementForm()
    context = {'form': form}
    return render(request, template_name, context)


@permission_required('evenementen.change_evenement')
def evenement_wijzig(request, slug):
    template_name = 'evenementen/evenement_wijzig.html'
    evenement = get_object_or_404(Evenement, slug=slug)
    if request.method == 'POST':
        form = EvenementForm(request.POST, instance=evenement)
        if form.is_valid():
            evenement = form.save()
            messages.success(request, "Evenement gewijzigd.")
            return redirect(evenement.get_absolute_url())
    else:
        form = EvenementForm(instance=evenement)
    context = {'evenement': evenement, 'form': form}
    return render(request, template_name, context)

src/evenementen/templates/evenementen/evenement_aanmeldingen.html
{% extends "mainscreen/base.html" %}

{% block title %}{{ evenement.naam }} | Aanmeldingen | UBR|V-Lab{% endblock %}

{% block navbar %}
<nav class="breadCrumbNav">
  <span class="assistive">U bevindt zich hier:</span>
  <a href="https://www.ubrijk.nl/organisatie/ubr/ubr-v-lab">UBR|V-Lab</a>
  <a href="{% url 'evenementen:evenementen' %}">Evenementen</a>
  <a href="{{ evenement.get_absolute_url }}">{{ evenement.naam }}</a>
  <span>Aanmeldingen</span>
</nav>
{% endblock %}

{% block content %}
<div id="content" class="article">
  <h1 class="news">Aanmeldingen voor {{ evenement.naam }}</h1>
  <p class="article-meta">Evenement</p>
  <dl>
    <dt>Datum:</dt>
    <dd>
      <time itemprop="startDate">{{ evenement.start_datum|date:"d F Y" }}</time>
      {% if evenement.einde_datum %} - <time itemprop="endDate">{{ evenement.einde_datum|date:"d F Y" }}</time>{% endif %}
    </dd>
	{% if evenement.locatie %}
    <dt>Locatie:</dt>
    <dd itemprop="location">{{ evenement.locatie }}</dd>
	{% endif %}
  </dl>
  <style>
    .intrinsic-container{position:relative;height:0;overflow:hidden;margin-bottom:1.5rem;}
	.intrinsic-container-16x9{padding-bottom:56.25%}
	.intrinsic-container-4x3{padding-bottom:75%}
	.intrinsic-container-1x2{padding-bottom:200%}
	.intrinsic-container iframe{position:absolute;top:0;left:0;width:100%;height:100%;margin:0!important;border:2px solid #ccc;}
  </style>
  <div class="intrinsic-container intrinsic-container-1x2">
    <iframe src="{% url 'survey:survey-result-data' id=evenement.aanmelding_formulier.pk %}" frameborder="0"></iframe>
  </div>
</div>
{% endblock %}

src/evenementen/templates/evenementen/evenement_evaluaties.html
{% extends "mainscreen/base.html" %}

{% block title %}{{ evenement.naam }} | Evaluaties | UBR|V-Lab{% endblock %}

{% block navbar %}
<nav class="breadCrumbNav">
  <span class="assistive">U bevindt zich hier:</span>
  <a href="https://www.ubrijk.nl/organisatie/ubr/ubr-v-lab">UBR|V-Lab</a>
  <a href="{% url 'evenementen:evenementen' %}">Evenementen</a>
  <a href="{{ evenement.get_absolute_url }}">{{ evenement.naam }}</a>
  <span>Evaluaties</span>
</nav>
{% endblock %}

{% block content %}
<div id="content" class="article">
  <h1 class="news">Evaluaties voor {{ evenement.naam }}</h1>
  <p class="article-meta">Evenement</p>
  <dl>
    <dt>Datum:</dt>
    <dd>
      <time itemprop="startDate">{{ evenement.start_datum|date:"d F Y" }}</time>
      {% if evenement.einde_datum %} - <time itemprop="endDate">{{ evenement.einde_datum|date:"d F Y" }}</time>{% endif %}
    </dd>
	{% if evenement.locatie %}
    <dt>Locatie:</dt>
    <dd itemprop="location">{{ evenement.locatie }}</dd>
	{% endif %}
  </dl>
  <style>
    .intrinsic-container{position:relative;height:0;overflow:hidden;margin-bottom:1.5rem;}
	.intrinsic-container-16x9{padding-bottom:56.25%}
	.intrinsic-container-4x3{padding-bottom:75%}
	.intrinsic-container-1x2{padding-bottom:200%}
	.intrinsic-container iframe{position:absolute;top:0;left:0;width:100%;height:100%;margin:0!important;border:2px solid #ccc;}
  </style>
  <div class="intrinsic-container intrinsic-container-1x2">
    <iframe src="{% url 'survey:survey-result-data' id=evenement.evaluatie_formulier.pk %}" frameborder="0"></iframe>
  </div>
</div>
{% endblock %}

src/evenementen/templates/evenementen/evenement_overzicht.html
{% extends "mainscreen/base.html" %}

{% block title %}{{ evenement.naam }} | Evenement | UBR|V-Lab{% endblock %}

{% block navbar %}
<nav class="breadCrumbNav">
  <span class="assistive">U bevindt zich hier:</span>
  <a href="https://www.ubrijk.nl/organisatie/ubr/ubr-v-lab">UBR|V-Lab</a>
  <a href="{% url 'evenementen:evenementen' %}">Evenementen</a>
  <span>{{ evenement.naam }}</span>
</nav>
{% endblock %}

{% block subnavigation %}
{% if evenement.aanmelding_formulier  or evenement.evaluatie_formulier %}
  <div class="subNavigation">
    <div class="wrapper">
      <ul>
	    {% if evenement.aanmelding_formulier.is_published %}
        <li><a href="{% url 'survey:survey-detail' id=evenement.aanmelding_formulier.id %}">Aanmelden</a></li>
	    {% elif evenement.evaluatie_formulier.is_published %}
        <li><a href="{% url 'survey:survey-detail' id=evenement.evaluatie_formulier.id %}">Evaluatie</a></li>
		{% endif %}
		{% if evenement.aanmelding_formulier.id and perms.evenementen.change_evenement %}
        <li><a href="{% url 'evenementen:evenement_aanmeldingen' slug=evenement.slug %}">Toon aanmeldingen</a></li>
		{% endif %}
		{% if evenement.evaluatie_formulier.id and perms.evenementen.change_evenement %}
        <li><a href="{% url 'evenementen:evenement_evaluaties' slug=evenement.slug %}">Toon evaluaties</a></li>
		{% endif %}
      </ul>
	  {% if evenement.programma %}
      <ul>
        <li><a href="{% url 'schedule:schedule_conference' slug=evenement.slug %}">Programma</a></li>
      </ul>
	  {% endif %}
	</div>
  </div>
{% elif evenement.programma %}
  <div class="subNavigation">
    <div class="wrapper">
      <ul>
        <li><a href="{% url 'schedule:schedule_conference' slug=evenement.slug %}">Programma</a></li>
      </ul>
	</div>
  </div>
{% endif %}
{% endblock %}

{% block content %}
<div id="content" class="article">
  <h1 class="news">{{ evenement.naam }}</h1>
  <p class="article-meta">Evenement</p>
  <dl>
    <dt>Datum:</dt>
    <dd>
      <time itemprop="startDate">{{ evenement.start_datum|date:"d F Y" }}</time>
      {% if evenement.einde_datum %} - <time itemprop="endDate">{{ evenement.einde_datum|date:"d F Y" }}</time>{% endif %}
    </dd>
	{% if evenement.locatie %}
    <dt>Locatie:</dt>
    <dd itemprop="location">{{ evenement.locatie }}</dd>
	{% endif %}
  </dl>
  {% if evenement.intro %}
  <div class="intro">
    <p>{{ evenement.intro|safe }}</p>
  </div>
  {% endif %}
{{ evenement.omschrijving|safe }}
</div>
{% if perms.evenementen.change_evenement %}
<div id="aside">
  <div class="brick linkBlock">
    <h2>Beheer</h2>
    <ul class="common">
      <li>
	    <a href="{% url 'admin:evenementen_evenement_change' evenement.pk %}" class="common">Wijzigen evenement</a>
      </li>
	  {% if evenement.aanmelding_formulier.pk %}
      <li>
	    <a href="{% url 'admin:survey_survey_change' evenement.aanmelding_formulier.pk %}" class="common">Wijzigen aanmelding formulier</a>
      </li>
	  {% else %}
      <li>
	    <a href="{% url 'admin:survey_survey_add' %}" class="common">Toevoegen aanmelding formulier</a>
      </li>
	  {% endif %}
	  {% if evenement.programma %}
      <li>
	    <a href="{% url 'conference:section_list' slug=evenement.slug %}" class="common">Wijzigen programma</a>
      </li>
	  {% else %}
      <li>
	    <a href="{% url 'admin:conference_conference_add' %}" class="common">Toevoegen programma</a>
      </li>
	  {% endif %}
	  {% if evenement.evaluatie_formulier.pk %}
      <li>
	    <a href="{% url 'admin:survey_survey_change' evenement.evaluatie_formulier.pk %}" class="common">Wijzigen evaluatie formulier</a>
      </li>
	  {% else %}
      <li>
	    <a href="{% url 'admin:survey_survey_add' %}" class="common">Toevoegen evaluatie formulier</a>
      </li>
	  {% endif %}
    </ul>
  </div>
</div>
{% endif %}
{% endblock %}

src/evenementen/templates/evenementen/evenementen.html
{% extends "mainscreen/base.html" %}

{% block title %}Evenementen | UBR|V-Lab{% endblock %}

{% block navbar %}
<nav class="breadCrumbNav">
	<span class="assistive">U bevindt zich hier:</span>
	<a href="https://www.ubrijk.nl/organisatie/ubr/ubr-v-lab">UBR|V-Lab</a>
	<span>Evenementen (actueel)</span>
</nav>
{% endblock %}

{% block subnavigation %}
  <div class="subNavigation">
    <div class="wrapper">
      <ul>
        <li><a href="{% url 'evenementen:historie' %}">Historie</a></li>
      </ul>
	</div>
  </div>
{% endblock %}

{% block content %}
<div id="content" class="article">
	{% if page.intro %}
	<div class="intro">
		<p>{{ page.intro|safe }}</p>
	</div>
	{% endif %}
	{{ page.content|safe }}
	<div class="common results">
		{% if evenement_list %}
		{% for evenement in evenement_list|dictsort:"start_datum" %}
		<a href="{{ evenement.get_absolute_url }}" class="activity">
			<h3>{{ evenement.naam }}</h3>
			{% if evenement.intro %}
			{{evenement.intro|safe|truncatewords_html:30}}
			{% else %}
			{{evenement.omschrijving|safe|truncatewords_html:30}}
			{% endif %}
			<p class="meta">
				{{ evenement.start_datum|date:"d F Y" }}
				{% if evenement.einde_datum %} - {{ evenement.einde_datum|date:"d F Y" }}{% endif %}
				{% if evenement.locatie %} | {{ evenement.locatie }}{% endif %}
				<br>Evenement
			</p>
		</a>
		{% endfor %}
		{% else %}
		<p>Er zijn geen actuele evenementen beschikbaar.</p>
		{% endif %}
	</div>
</div>
{% if perms.evenementen.add_evenement %}
<div id="aside">
	<div class="block">
		<h2>Beheer</h2>
		<ul class="common">
			{% if perms.evenementen.add_evenement %}
			<li>
				<a href="{% url 'admin:evenementen_evenement_add' %}" class="common">Toevoegen evenement</a>
			</li>
			{% endif %}
			{% if perms.evenementen.change_pagecontent %}
			<li>
				<a href="{% url 'admin:evenementen_pagecontent_change' page.pk %}" class="common">Wijzigen pagina inhoud</a>
			</li>
			{% endif %}
		</ul>
	</div>
</div>
{% endif %}
{% endblock %}

src/evenementen/templates/evenementen/historie.html
{% extends "mainscreen/base.html" %}

{% block title %}Evenementen | UBR|V-Lab{% endblock %}

{% block navbar %}
<nav class="breadCrumbNav">
    <span class="assistive">U bevindt zich hier:</span>
    <a href="https://www.ubrijk.nl/organisatie/ubr/ubr-v-lab">UBR|V-Lab</a>
    <span>Evenementen (historie)</span>
</nav>
{% endblock %}

{% block subnavigation %}
  <div class="subNavigation">
    <div class="wrapper">
      <ul>
        <li><a href="{% url 'evenementen:evenementen' %}">Actueel</a></li>
      </ul>
	</div>
  </div>
{% endblock %}

{% block content %}
<div id="content" class="article">
    {% if page.intro %}
    <div class="intro">
        <p>{{ page.intro|safe }}</p>
    </div>
    {% endif %}
    {{ page.content|safe }}
    <div class="common results">
        {% if evenement_list %}
        {% for evenement in evenement_list|dictsortreversed:"start_datum" %}
        <a href="{{ evenement.get_absolute_url }}" class="activity">
            <h3>{{ evenement.naam }}</h3>
            {% if evenement.intro %}
            {{evenement.intro|safe|truncatewords_html:30}}
            {% else %}
            {{evenement.omschrijving|safe|truncatewords_html:30}}
            {% endif %}
            <p class="meta">
                {{ evenement.start_datum|date:"d F Y" }}
                {% if evenement.einde_datum %} - {{ evenement.einde_datum|date:"d F Y" }}{% endif %}
                {% if evenement.locatie %} | {{ evenement.locatie }}{% endif %}
                <br>Evenement
            </p>
        </a>
        {% endfor %}
        {% else %}
        <p>Er zijn geen historische evenementen beschikbaar.</p>
        {% endif %}
    </div>
</div>
{% if perms.evenementen.add_evenement %}
<div id="aside">
    <div class="block">
        <h2>Beheer</h2>
        <ul class="common">
            {% if perms.evenementen.add_evenement %}
            <li>
                <a href="{% url 'admin:evenementen_evenement_add' %}" class="common">Toevoegen evenement</a>
            </li>
            {% endif %}
            {% if perms.evenementen.change_pagecontent %}
            <li>
                <a href="{% url 'admin:evenementen_pagecontent_change' page.pk %}" class="common">Wijzigen pagina inhoud</a>
            </li>
            {% endif %}
        </ul>
    </div>
</div>
{% endif %}
{% endblock %}